### ISSUE TITLE
Shapekey Driver ->  Easy Driver Set Up

### ISSUE THREAD

**Issue by LMJulianS** [ndee85/Driver-Constraint-Addon#1]
Hi,
I would like to start with saying that your work is awesome!

But why do you only support Shapekeys (to be driven) and Bones (as Driver).
It would be cool to use any object as an driver.
Further more i would like the "Custom Propertys" of an object to apear as an "Type" like x or z Axis do for example.

**Comment by ndee85** [comment]
I added this feature now. Any object can be a driver. The addon just uses the active object or bone as driver. Fixed with this commit  5d6d076743dfbc54eeb5d8067fe10e36cc8de624
