### ISSUE TITLE
get limit problem

### ISSUE THREAD

**Issue by johantri** [ndee85/Driver-Constraint-Addon#2]
Hi ndee85, thanks for this addon. I found a problem when get limit activated. I thought it will add a limit location constraint automatically to the bone, but it doesn't. Can you check if this is not a bug? I'm using Blender 2.76. Thanks again! :)

**Comment by ndee85** [comment]
I added this feature now. You have an extra checkbox for creating limits.
Fixed with this commit 5d6d076743dfbc54eeb5d8067fe10e36cc8de624
