### ISSUE TITLE
repeated error message in 2.79

### ISSUE THREAD

**Issue by Hammers69** [ndee85/Driver-Constraint-Addon#5]
Hi Andy,

Love the addon so much, but am having some trouble with it now that I've got to the crunch with my character. I had no problems testing it and using it earlier with 2.79, but now that the character is fully rigged etc. I'm getting an (out of range?) error whenever I try to initiate adding a shapekey constraint. I'm using the latest version of the addon. If I use Blender 2.78 with 1.24 addon it seems to work (at least the UI—there were still problems getting bad mappings in the driver curve).

Can you shed any light for me, or would you like me to send my file?

Thanks so much,

Stephen.
![screen shot 2018-09-22 at 6 52 55 pm](https://user-images.githubusercontent.com/38600234/45922779-b0bb8600-bf18-11e8-826d-7be35ab19f17.png)

**Comment by ndee85** [comment]
Hi Stephen,
please try the latest git version. Not the one from the releases folder. Therefore download the full repository and zip the driver_constraint_addon and install that zip file.

If the error persists, would it be possible to attach a file where this error occurs? That way it would be easier to fix the isssue.

**Comment by Hammers69** [comment]
Thanks Andy, I tried reinstalling as you suggested but have the same problem. I'll try attaching my actual .blend here for you to take a look at. The addon seems to be fine in simpler files, just not sure why it's misbehaving with my rig. Cheers!

[Heartly_02-16.blend.zip](https://github.com/ndee85/Driver-Constraint-Addon/files/2409721/Heartly_02-16.blend.zip)

**Comment by Hammers69** [comment]
Sorry, this is a different issue but thought I'd add to my post... I've also been unable to get the addon to control a curve shape-key, including copying and pasting the data path of the shape key property. Have I missed something? I realise this is an unusual scenario, but I use these at times. Cheers.

**Comment by ndee85** [comment]
Hi Hammer,
just pushed a fix for your Heartly_02 blend. Please clone the latest github version and copy the driver_constraint_addon folder into your blender addon folder and see if it works. I hope the error is fixed.

About driving curve shapekeys. This is not implemented, as I didn't know shapekeys existed for curves :-)
I would need to investigate on that topic.

**Comment by ndee85** [comment]
Ok. Just pushed a new commit which also enables the addon to work with curve objects. Please try if you can drive shapekeys for curves.

Would be great if you report back.

**Comment by Hammers69** [comment]
Fantastic Andy, All seems to be working now, and thanks for the curve shapekey option. I wonder if anyone else uses these... :)

**Comment by ndee85** [comment]
Great. Good to know everything works now. Closing issue.
